version: '3.1'

services:
  app:
    build: .
    command: ["scripts/wait-for-it.sh", "db:5432", "--", "scripts/start.sh"]
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      APP_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      APP_DATABASE_HOST: db
      APP_DATABASE_USER: postgres
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    links:
      - "db"
    volumes:
      - ".:/home/deploy/current"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
